include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore

  exclude:
    - lib/core/ui/pixel_icons.dart
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

linter:
  rules:
    - always_declare_return_types
    - avoid_dynamic_calls
    - avoid_print
    - await_only_futures
    - directives_ordering
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_single_quotes
    - require_trailing_commas
    - sort_child_properties_last
    - unawaited_futures
    - unnecessary_lambdas
    - use_super_parameters
